-- MySQL Script generated by MySQL Workbench
-- Thu 23 Feb 2017 04:46:15 PM CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema udemy_php
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema udemy_php
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `udemy_php` DEFAULT CHARACTER SET utf8 ;
USE `udemy_php` ;

-- -----------------------------------------------------
-- Table `udemy_php`.`Accounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `udemy_php`.`Accounts` ;

CREATE TABLE IF NOT EXISTS `udemy_php`.`Accounts` (
  `account_id` INT NOT NULL AUTO_INCREMENT,
  `account_username` VARCHAR(45) NULL,
  `account_password` VARCHAR(45) NULL,
  `account_email` VARCHAR(45) NULL,
  `account_first_name` VARCHAR(45) NULL,
  `account_last_name` VARCHAR(45) NULL,
  PRIMARY KEY (`account_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `udemy_php`.`Tasks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `udemy_php`.`Tasks` ;

CREATE TABLE IF NOT EXISTS `udemy_php`.`Tasks` (
  `task_id` INT NOT NULL AUTO_INCREMENT,
  `task_text` VARCHAR(45) NULL,
  `task_deadline` DATE NULL,
  `account_id` INT NOT NULL,
  PRIMARY KEY (`task_id`),
  INDEX `fk_Tasks_Accounts_idx` (`account_id` ASC),
  CONSTRAINT `fk_Tasks_Accounts`
    FOREIGN KEY (`account_id`)
    REFERENCES `udemy_php`.`Accounts` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
